import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import { VerticalMenu, ThemeColorPicker } from './components'
import { styles } from './layout.css'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className={styles.layout}>
          <div className={styles.grid}>
            <VerticalMenu />
            <div className={styles.content}>
              {children}
              <ThemeColorPicker />
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
